// <auto-generated />
using System;
using CallTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTrack.Data.Migrations
{
    [DbContext(typeof(CallTrackContext))]
    [Migration("20241227125407_FIX-Relationship_1")]
    partial class FIXRelationship_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CallTrack.Domain.entities.Analyst", b =>
                {
                    b.Property<long>("AnalystId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analyst_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AnalystId"));

                    b.Property<string>("AnalystName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("analyst_name");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    b.Property<int>("StatusAnalyst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4)
                        .HasColumnName("analyst_status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AnalystId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("analysts", (string)null);
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Calls", b =>
                {
                    b.Property<long>("CallId")
                        .HasColumnType("bigint")
                        .HasColumnName("call_id");

                    b.Property<long>("AnalystId")
                        .HasColumnType("bigint")
                        .HasColumnName("analyst_id");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("call_close_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("call_code");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("call_observation");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("call_open_date");

                    b.Property<long>("ReasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("reason_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_status");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_type");

                    b.HasKey("CallId");

                    b.HasIndex("AnalystId");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Managers", b =>
                {
                    b.Property<long>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ManagerId"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manager_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ManagerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Reasons", b =>
                {
                    b.Property<long>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reason_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ReasonId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason_description");

                    b.HasKey("ReasonId")
                        .HasName("reason_id");

                    b.ToTable("reasons", (string)null);

                    b.HasData(
                        new
                        {
                            ReasonId = 1L,
                            Description = "PIX"
                        },
                        new
                        {
                            ReasonId = 2L,
                            Description = "Saldo Bloqueado"
                        },
                        new
                        {
                            ReasonId = 3L,
                            Description = "Fila Errada"
                        },
                        new
                        {
                            ReasonId = 4L,
                            Description = "Duplicado"
                        },
                        new
                        {
                            ReasonId = 5L,
                            Description = "Erro de acesso ao app"
                        },
                        new
                        {
                            ReasonId = 6L,
                            Description = "Orientação"
                        },
                        new
                        {
                            ReasonId = 7L,
                            Description = "Erro Geral / Intermitência"
                        },
                        new
                        {
                            ReasonId = 8L,
                            Description = "Cancelamento de Cartão"
                        },
                        new
                        {
                            ReasonId = 9L,
                            Description = "Cancelamento Conta"
                        },
                        new
                        {
                            ReasonId = 10L,
                            Description = "Alteração Cadastral"
                        },
                        new
                        {
                            ReasonId = 11L,
                            Description = "Alteração de Type"
                        },
                        new
                        {
                            ReasonId = 12L,
                            Description = "Conta Topázio"
                        },
                        new
                        {
                            ReasonId = 13L,
                            Description = "Desassociação"
                        },
                        new
                        {
                            ReasonId = 14L,
                            Description = "Redefinição de Senha"
                        },
                        new
                        {
                            ReasonId = 15L,
                            Description = "SMS"
                        },
                        new
                        {
                            ReasonId = 16L,
                            Description = "Token de Ativação"
                        },
                        new
                        {
                            ReasonId = 17L,
                            Description = "Chip APAG"
                        },
                        new
                        {
                            ReasonId = 18L,
                            Description = "Maquininha"
                        },
                        new
                        {
                            ReasonId = 19L,
                            Description = "QR Code"
                        },
                        new
                        {
                            ReasonId = 20L,
                            Description = "Saque Tecban"
                        },
                        new
                        {
                            ReasonId = 21L,
                            Description = "Transferencia"
                        },
                        new
                        {
                            ReasonId = 22L,
                            Description = "Devolução da Maquininha"
                        },
                        new
                        {
                            ReasonId = 23L,
                            Description = "Conta congelada"
                        },
                        new
                        {
                            ReasonId = 24L,
                            Description = "Conta encerrada"
                        },
                        new
                        {
                            ReasonId = 25L,
                            Description = "Conta Bloqueada"
                        },
                        new
                        {
                            ReasonId = 26L,
                            Description = "Chamado Teste"
                        },
                        new
                        {
                            ReasonId = 27L,
                            Description = "Credito em Conta"
                        },
                        new
                        {
                            ReasonId = 28L,
                            Description = "Não aparece conta/cartao"
                        },
                        new
                        {
                            ReasonId = 29L,
                            Description = "Parâmetros Inválidos APP"
                        },
                        new
                        {
                            ReasonId = 30L,
                            Description = "Parâmetros Inválidos Maquininha"
                        },
                        new
                        {
                            ReasonId = 31L,
                            Description = "Relatorio de vendas app"
                        },
                        new
                        {
                            ReasonId = 32L,
                            Description = "Transação APAG"
                        },
                        new
                        {
                            ReasonId = 33L,
                            Description = "Reset de Chip"
                        },
                        new
                        {
                            ReasonId = 34L,
                            Description = "Cancelamento Transação"
                        },
                        new
                        {
                            ReasonId = 35L,
                            Description = "Estorno Adesão Apag"
                        },
                        new
                        {
                            ReasonId = 36L,
                            Description = "Efeito de Contrato"
                        },
                        new
                        {
                            ReasonId = 37L,
                            Description = "Boleto Pagamento"
                        },
                        new
                        {
                            ReasonId = 38L,
                            Description = "Informe de rendimentos"
                        },
                        new
                        {
                            ReasonId = 39L,
                            Description = "E-mail Suspeito"
                        },
                        new
                        {
                            ReasonId = 40L,
                            Description = "Bloqueio judicial"
                        },
                        new
                        {
                            ReasonId = 41L,
                            Description = "Recarga Bilhete Único"
                        },
                        new
                        {
                            ReasonId = 42L,
                            Description = "Erro de Biometria"
                        },
                        new
                        {
                            ReasonId = 43L,
                            Description = "Sem Grupo de Acesso"
                        },
                        new
                        {
                            ReasonId = 44L,
                            Description = "Sem Cadastro de Loja"
                        },
                        new
                        {
                            ReasonId = 45L,
                            Description = "Proposta Recusada"
                        },
                        new
                        {
                            ReasonId = 46L,
                            Description = "Sem Limite para Beneficio"
                        },
                        new
                        {
                            ReasonId = 47L,
                            Description = "Erro Sistêmico"
                        });
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<long>("AnalystId")
                        .HasColumnType("bigint")
                        .HasColumnName("analyst_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_email");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_password");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Analyst", b =>
                {
                    b.HasOne("CallTrack.Domain.entities.Managers", "Manager")
                        .WithMany("Analysts")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_analysts_managers_ManagerId");

                    b.HasOne("CallTrack.Domain.entities.Users", "User")
                        .WithOne("Analyst")
                        .HasForeignKey("CallTrack.Domain.entities.Analyst", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_id");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Calls", b =>
                {
                    b.HasOne("CallTrack.Domain.entities.Analyst", "Analyst")
                        .WithMany("Calls")
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CallTrack.Domain.entities.Reasons", "Reasons")
                        .WithMany("Calls")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");

                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Managers", b =>
                {
                    b.HasOne("CallTrack.Domain.entities.Users", "User")
                        .WithOne("Manager")
                        .HasForeignKey("CallTrack.Domain.entities.Managers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Analyst", b =>
                {
                    b.Navigation("Calls");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Managers", b =>
                {
                    b.Navigation("Analysts");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Reasons", b =>
                {
                    b.Navigation("Calls");
                });

            modelBuilder.Entity("CallTrack.Domain.entities.Users", b =>
                {
                    b.Navigation("Analyst")
                        .IsRequired();

                    b.Navigation("Manager")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
