// <auto-generated />
using System;
using CallTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTrack.Data.Migrations
{
    [DbContext(typeof(CallTrackContext))]
    partial class CallTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.Property<long>("analystId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analyst_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("analystId"));

                    b.Property<long?>("ManagersManagerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsersUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("analystName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("analyst_name");

                    b.Property<int>("statusAnalyst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4)
                        .HasColumnName("analyst_status");

                    b.HasKey("analystId");

                    b.HasIndex("ManagersManagerId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("analysts", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.Property<long>("callId")
                        .HasColumnType("bigint")
                        .HasColumnName("call_id");

                    b.Property<DateTime>("close_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("call_code");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("call_observation");

                    b.Property<DateTime>("open_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_status");

                    b.Property<int>("type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_type");

                    b.HasKey("callId");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Managers", b =>
                {
                    b.Property<long>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ManagerId"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manager_name");

                    b.Property<long?>("UsersUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ManagerId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Reasons", b =>
                {
                    b.Property<long>("ReasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("reason_id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason_description");

                    b.HasKey("ReasonId")
                        .HasName("reason_id");

                    b.ToTable("reasons", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_password");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Managers", null)
                        .WithMany("analysts")
                        .HasForeignKey("ManagersManagerId");

                    b.HasOne("CallTrack.Data.entities.Users", null)
                        .WithMany("analysts")
                        .HasForeignKey("UsersUserId");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Analyst", "analyst")
                        .WithMany("calls")
                        .HasForeignKey("callId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("analyst");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Managers", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Users", null)
                        .WithMany("managers")
                        .HasForeignKey("UsersUserId");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Reasons", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Calls", "calls")
                        .WithMany("reasons")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("calls");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.Navigation("calls");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.Navigation("reasons");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Managers", b =>
                {
                    b.Navigation("analysts");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Users", b =>
                {
                    b.Navigation("analysts");

                    b.Navigation("managers");
                });
#pragma warning restore 612, 618
        }
    }
}
