// <auto-generated />
using System;
using CallTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTrack.Data.Migrations
{
    [DbContext(typeof(CallTrackContext))]
    partial class CallTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.Property<long>("analystId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("analyst_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("analystId"));

                    b.Property<string>("analystName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("analyst_name");

                    b.Property<long>("managerId")
                        .HasColumnType("bigint");

                    b.Property<int>("statusAnalyst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4)
                        .HasColumnName("analyst_status");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("analystId");

                    b.HasIndex("managerId");

                    b.HasIndex("userId");

                    b.ToTable("analysts", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.Property<long>("callId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("call_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("callId"));

                    b.Property<long?>("analystId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("closeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("call_close_date");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("call_code");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("call_observation");

                    b.Property<DateTime>("openDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("call_open_date");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_status");

                    b.Property<int>("type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("call_type");

                    b.HasKey("callId");

                    b.HasIndex("analystId");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Managers", b =>
                {
                    b.Property<long>("managerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("managerId"));

                    b.Property<string>("managerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manager_name");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("managerId");

                    b.HasIndex("userId");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Reasons", b =>
                {
                    b.Property<long>("reasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reason_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("reasonId"));

                    b.Property<long?>("CallscallId")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason_description");

                    b.HasKey("reasonId")
                        .HasName("reason_id");

                    b.HasIndex("CallscallId");

                    b.ToTable("reasons", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Users", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_email")
                        .HasAnnotation("Relational:CheckConstraint", "email LIKE '%@%.%'");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_password");

                    b.HasKey("userId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Managers", "manager")
                        .WithMany()
                        .HasForeignKey("managerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CallTrack.Data.entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Analyst", null)
                        .WithMany("calls")
                        .HasForeignKey("analystId");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Managers", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Reasons", b =>
                {
                    b.HasOne("CallTrack.Data.entities.Calls", null)
                        .WithMany("reasons")
                        .HasForeignKey("CallscallId");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Analyst", b =>
                {
                    b.Navigation("calls");
                });

            modelBuilder.Entity("CallTrack.Data.entities.Calls", b =>
                {
                    b.Navigation("reasons");
                });
#pragma warning restore 612, 618
        }
    }
}
